export const OWNER_DATA_KEY = "data_of_author"
export const AUTHOR_MID = "tweet_author_id"
export const RETWEET_COUNT = "tweet_retweet_count"
export const BOOKMARK_COUNT = "tweet_bookmark_count"
export const LIKE_COUNT = "tweet_like_count"
export const COMMENT_COUNT = "tweet_comment_count"
export const RETWEET_LIST = "tweet_retweet_list"
export const COMMENT_LIST = "comment_list_key"
export const LIKE_LIST = "tweet_like_list"     // users who liked this tweet
export const CONTENT = "content_key"
export const ORIGINAL_TWEET = "original_tweet_mid"
export const ATTACHMENTS = "attachements_key"
export const PRIVACY = "privacy_key"
export const TWT_CONTENT_KEY = "core_data_of_tweet"
const CHAT_SESSION_LIST = "chat_session_list"

// Keys in App mimei database
export const TWT_LIST_KEY = "list_of_tweets_mid"
export const FOLLOWINGS_LIST = "list_of_followings_mid"
export const FOLLOWERS_LIST = "list_of_followers_mid"
export const FANS_COUNT = "user_followers_count"
export const FOLLOWINGS_COUNT = "user_followings_count"
